### PR TITLE
feature: Update sponsor list to reflect UTD CS department

### LINKED ISSUE #12: Update sponsors to reflect CS Department funding
# Overview
The sponsors section needs to be updated to reflect the following:
- The Jonsson School Computer Science Department, not the Jonsson School itself, is providing fiscal sponsorship for the event.
- The CS Department is a current sponsor, not a past sponsor.

### PR DESCRIPTION
**Pull request by SaminKhan35**
Closes #12.

This PR adds logos for the Center for AI and ML at UTD and updates UTD CS Department logo.

### CODE REVIEW

**Review by adityarathod — CHANGES_REQUESTED** [review]
I think you forgot to commit the images. The deploy preview is broken. 😄

**Review by adityarathod — APPROVED** [review]
LGTM! @WillieCubed can you complete your review too so we can merge by midnight tonight?

**Comment by WillieCubed** [comment]
I just made some changes, so now this LGTM!

**Review by WillieCubed — APPROVED** [review]
We're all set to merge now.

**Pull request merged**
